Repository kubenow/docs, pull requests merged in 2018-04, with the labels that each got.

#30 Adding Advanced Topics Section
  advanced_topics/cloudflare-dns.rst
  advanced_topics/cloudflare-proxied.rst
  advanced_topics/edge-nodes.rst
  advanced_topics/glusterfs-nodes.rst
  advanced_topics/single-node-deployments.rst
  index.rst
Labels: documentation, enhancement

#31 Rename terraform.tfvars to config.tfvars
  advanced_topics/cloudflare-dns.rst
  advanced_topics/cloudflare-proxied.rst
  advanced_topics/edge-nodes.rst
  advanced_topics/glusterfs-nodes.rst
  advanced_topics/single-node-deployments.rst
  getting_started/bootstrap.rst
Labels: release-0.4

#33 Updating GlusterFS advanced section
  advanced_topics/glusterfs-nodes.rst
Labels: stable/0.3

#32 Updating prerequisites.rst
  getting_started/prerequisites.rst
Labels: documentation, stable/0.3
